"""Single-view and multi-view localisation models and training protocol.

Public surface:

- **Models** — single-view encoders/heads, frozen experts, camera-view fusion,
  and illumination fusion localisers
- **Builders** — architecture grids, freeze records, and factory helpers
  (:mod:`builders`)
- **Capability protocol** — shared train subsets, overfitability testing, and
  full-split training (:mod:`architecture_capability`)

Train/validation/test splits are always by ``sequence_id``. Overfitability
stages must not leak validation or test rows into subset draws.
"""

from .alternative_localizer import (
    LocalizeMeanPool,
    LocalizeSingleView,
    LocalizeSingleViewFlatten,
    LocalizeSingleViewFourier,
)
from .architecture_capability import (
    SharedSubset,
    build_shared_subsets,
    evaluate_split_rmse,
    run_stage1_overfitability,
    summarize_stage1,
    train_full_split,
)
from .builders import (
    ArchitectureFreezeRecord,
    CHANNEL_PRESETS,
    NormalisationSpec,
    OpticalRegimeSpec,
    RepresentationSpec,
    SingleViewArchConfig,
    SingleViewBlockFreezeRecord,
    build_from_config,
    count_parameters,
    default_mechanism_grid,
    describe_feature_geometry,
    make_encode,
    make_flatten,
    make_fourier,
    make_pooled,
    materialize_lazy_modules,
    win3b_receptive_field_grid,
    win3c_channel_capacity_grid,
    win3d_head_expressiveness_grid,
    win3e_architecture_freeze,
    win3e_control_configs,
    win3f_representation_grid,
    win3f_selected_representation,
    win3g_normalisation_grid,
    win3g_selected_normalisation,
    win3h_optical_regime_grid,
    m8_single_view_block_freeze,
    win3i_key_result_sources,
    win3j_single_view_freeze,
)
from .encoder import Encode
from .fourier_pool import FourierCodedPool2d, enumerate_fourier_modes
from .localizer import LocalizerSingleViewFourier
from .localize_multiview import (
    FUSION_PATTERN_09_0,
    FUSION_PATTERN_09_1,
    FUSION_PATTERN_09_1_DEEPSETS_FOURIER,
    FUSION_PATTERN_09_1_DEEPSETS_NO_FOURIER,
    FUSION_PATTERN_09_1_MEAN_POOL,
    FUSION_PATTERN_09_1_MEAN_POOL_POOLED,
    FUSION_PATTERN_09_1_POOLED,
    FUSION_PATTERN_09_2,
    FUSION_PATTERN_09_2_POOLED,
    FUSION_PATTERN_09_3,
    FUSION_PATTERN_09_3_POOLED,
    FUSION_PATTERN_10_BASELINE,
    FUSION_PATTERN_10_BASELINE_POOLED,
    FUSION_PATTERN_10_1_C,
    FUSION_PATTERN_10_1_C_POOLED,
    FUSION_PATTERN_10_1_C_FROZEN,
    FUSION_PATTERN_10_1_C_FROZEN_POOLED,
    FUSION_PATTERN_10_1_D,
    FUSION_PATTERN_10_1_D_POOLED,
    FUSION_PATTERN_10_1_D_FROZEN,
    FUSION_PATTERN_10_1_D_FROZEN_POOLED,
    FUSION_PATTERN_10_2,
    GEOMETRY_MODE_CONCAT,
    GEOMETRY_MODE_FILM,
    M9_1_DEEPSETS_PHI_HIDDEN,
    M9_1_DEEPSETS_RHO_HIDDEN,
    M9_2_FUSION_DEPTH,
    M9_2_FUSION_HIDDEN,
    M9_3_FUSION_DEPTH,
    M9_3_FUSION_HIDDEN,
    M10_BASELINE_FUSION_DEPTH,
    M10_BASELINE_FUSION_HIDDEN,
    M10_1_FUSION_DEPTH,
    M10_1_FUSION_HIDDEN,
    M10_2_CAMERA_LATENT_DIM,
    M10_2_FUSION_DEPTH,
    M10_2_FUSION_HIDDEN,
    M10_LIGHT_ANGLES_DEG,
    PACKING_MEAN_POOL,
    PACKING_ORDERED_CONCAT,
    AngleConditionFiLM,
    CompactLatentFusionLocalizer,
    DeepSetsFusionHead,
    ExpertXyzMeanLocalizer,
    FrozenEncoderDeepSetsLocalizer,
    GeometryAwareFourierFusionLocalizer,
    HierarchicalLightThenCameraFusionLocalizer,
    MeanLatentFusionLocalizer,
    fuse_coordinates,
    light_angle_deg_from_optical_setup_id,
    make_angle_features,
    mean_coordinates,
    new_frozen_pooled_single_view_expert,
    new_frozen_single_view_expert,
    pack_geometry_tokens,
    pack_illumination_geometry_tokens,
    shared_xyz_mean,
)

__all__ = [
    "ArchitectureFreezeRecord",
    "CHANNEL_PRESETS",
    "CompactLatentFusionLocalizer",
    "DeepSetsFusionHead",
    "Encode",
    "ExpertXyzMeanLocalizer",
    "FUSION_PATTERN_09_0",
    "FUSION_PATTERN_09_1",
    "FUSION_PATTERN_09_1_DEEPSETS_FOURIER",
    "FUSION_PATTERN_09_1_DEEPSETS_NO_FOURIER",
    "FUSION_PATTERN_09_1_MEAN_POOL",
    "FUSION_PATTERN_09_1_MEAN_POOL_POOLED",
    "FUSION_PATTERN_09_1_POOLED",
    "FUSION_PATTERN_09_2",
    "FUSION_PATTERN_09_2_POOLED",
    "FUSION_PATTERN_09_3",
    "FUSION_PATTERN_09_3_POOLED",
    "FUSION_PATTERN_10_BASELINE",
    "FUSION_PATTERN_10_BASELINE_POOLED",
    "FUSION_PATTERN_10_1_C",
    "FUSION_PATTERN_10_1_C_POOLED",
    "FUSION_PATTERN_10_1_C_FROZEN",
    "FUSION_PATTERN_10_1_C_FROZEN_POOLED",
    "FUSION_PATTERN_10_1_D",
    "FUSION_PATTERN_10_1_D_POOLED",
    "FUSION_PATTERN_10_1_D_FROZEN",
    "FUSION_PATTERN_10_1_D_FROZEN_POOLED",
    "FUSION_PATTERN_10_2",
    "FrozenEncoderDeepSetsLocalizer",
    "GEOMETRY_MODE_CONCAT",
    "GEOMETRY_MODE_FILM",
    "AngleConditionFiLM",
    "M9_1_DEEPSETS_PHI_HIDDEN",
    "M9_1_DEEPSETS_RHO_HIDDEN",
    "M9_2_FUSION_DEPTH",
    "M9_2_FUSION_HIDDEN",
    "M9_3_FUSION_DEPTH",
    "M9_3_FUSION_HIDDEN",
    "M10_BASELINE_FUSION_DEPTH",
    "M10_BASELINE_FUSION_HIDDEN",
    "M10_1_FUSION_DEPTH",
    "M10_1_FUSION_HIDDEN",
    "M10_2_CAMERA_LATENT_DIM",
    "M10_2_FUSION_DEPTH",
    "M10_2_FUSION_HIDDEN",
    "M10_LIGHT_ANGLES_DEG",
    "PACKING_MEAN_POOL",
    "PACKING_ORDERED_CONCAT",
    "FourierCodedPool2d",
    "GeometryAwareFourierFusionLocalizer",
    "HierarchicalLightThenCameraFusionLocalizer",
    "LocalizeMeanPool",
    "LocalizeSingleView",
    "LocalizeSingleViewFlatten",
    "LocalizeSingleViewFourier",
    "LocalizerSingleViewFourier",
    "MeanLatentFusionLocalizer",
    "NormalisationSpec",
    "OpticalRegimeSpec",
    "RepresentationSpec",
    "SharedSubset",
    "SingleViewArchConfig",
    "SingleViewBlockFreezeRecord",
    "build_from_config",
    "build_shared_subsets",
    "count_parameters",
    "default_mechanism_grid",
    "describe_feature_geometry",
    "enumerate_fourier_modes",
    "evaluate_split_rmse",
    "fuse_coordinates",
    "light_angle_deg_from_optical_setup_id",
    "make_angle_features",
    "make_encode",
    "make_flatten",
    "make_fourier",
    "make_pooled",
    "materialize_lazy_modules",
    "mean_coordinates",
    "new_frozen_pooled_single_view_expert",
    "new_frozen_single_view_expert",
    "pack_geometry_tokens",
    "pack_illumination_geometry_tokens",
    "run_stage1_overfitability",
    "shared_xyz_mean",
    "summarize_stage1",
    "train_full_split",
    "win3b_receptive_field_grid",
    "win3c_channel_capacity_grid",
    "win3d_head_expressiveness_grid",
    "win3e_architecture_freeze",
    "win3e_control_configs",
    "win3f_representation_grid",
    "win3f_selected_representation",
    "win3g_normalisation_grid",
    "win3g_selected_normalisation",
    "win3h_optical_regime_grid",
    "win3i_key_result_sources",
    "m8_single_view_block_freeze",
    "win3j_single_view_freeze",
]
