"""Reusable localisation study protocols for milestone notebooks.

Notebooks should call these helpers rather than inlining Adam/MSE loops.
"""

from .single_view_m8 import (
    ARCH_COLORS,
    ARCH_ORDER,
    CANONICAL_LR_BY_ARCH,
    DEFAULT_LR_GRID,
    DEFAULT_LR_STUDY_CHECKPOINT,
    DEFAULT_SENSITIVITY_SPLIT_SEEDS,
    LearningRateStudyResult,
    M8_CANONICAL_LR_BY_ARCH,
    SplitSensitivityStudyResult,
    TrainValTestStudyResult,
    dummy_batch_from_dataset,
    make_m8_single_view_model,
    make_win3a_model,
    particle_setup_id_for_row,
    probe_m8_parameter_counts,
    probe_win3a_parameter_counts,
    relabel_catalog_rows_for_split_seed,
    rmse_metrics_from_l2_errors,
    run_learning_rate_study,
    run_split_sensitivity_study,
    run_train_val_test_study,
    select_lr_by_arch,
    set_train_seed,
)
from .study_checkpoints import (
    M08_LEARNING_RATE_STUDY,
    M08_TRAIN_VAL_TEST_XYZ,
    M08_TRAIN_VAL_TEST_Z,
    M08_XYZ_SPLIT_SENSITIVITY,
    M09_E2E_FOURIER_GEOMETRY_FUSION,
    M09_E2E_POOLED_GEOMETRY_FUSION,
    M09_FROZEN_FOURIER_FUSION,
    M09_FROZEN_POOLED_FUSION,
    M10_E2E_ILLUMINATION_FUSION,
    M10_FROZEN_ILLUMINATION_FUSION,
    M10_HIERARCHICAL_LIGHT_THEN_CAMERA,
    StudyCheckpointPolicy,
    study_checkpoint_path,
    study_checkpoint_policy,
    study_results_dir,
)
from .m10_illumination_fusion import (
    M10IlluminationConfig,
    M10IlluminationResult,
    run_m10_illumination_fusion,
)
from .m10_hierarchical_fusion import (
    M10HierarchicalConfig,
    M10HierarchicalResult,
    run_m10_hierarchical_fusion,
)
from .m9_frozen_fusion import (
    DEFAULT_LR_STAGE_B,
    DEFAULT_LR_STAGE_B_GRID,
    M9FusionConfig,
    M9FusionFamilyResult,
    run_fusion_lr_study,
    run_m9_frozen_fusion_family,
)
from .m9_e2e_geometry_fusion import (
    M9E2EConfig,
    M9E2EFamilyResult,
    run_m9_e2e_geometry_fusion_family,
)

__all__ = [
    "ARCH_COLORS",
    "ARCH_ORDER",
    "CANONICAL_LR_BY_ARCH",
    "DEFAULT_LR_GRID",
    "DEFAULT_LR_STAGE_B",
    "DEFAULT_LR_STAGE_B_GRID",
    "DEFAULT_LR_STUDY_CHECKPOINT",
    "DEFAULT_SENSITIVITY_SPLIT_SEEDS",
    "LearningRateStudyResult",
    "M08_LEARNING_RATE_STUDY",
    "M08_TRAIN_VAL_TEST_XYZ",
    "M08_TRAIN_VAL_TEST_Z",
    "M08_XYZ_SPLIT_SENSITIVITY",
    "M09_E2E_FOURIER_GEOMETRY_FUSION",
    "M09_E2E_POOLED_GEOMETRY_FUSION",
    "M09_FROZEN_FOURIER_FUSION",
    "M09_FROZEN_POOLED_FUSION",
    "M10_E2E_ILLUMINATION_FUSION",
    "M10_FROZEN_ILLUMINATION_FUSION",
    "M10_HIERARCHICAL_LIGHT_THEN_CAMERA",
    "M10HierarchicalConfig",
    "M10HierarchicalResult",
    "M10IlluminationConfig",
    "M10IlluminationResult",
    "M8_CANONICAL_LR_BY_ARCH",
    "M9E2EConfig",
    "M9E2EFamilyResult",
    "M9FusionConfig",
    "M9FusionFamilyResult",
    "SplitSensitivityStudyResult",
    "StudyCheckpointPolicy",
    "TrainValTestStudyResult",
    "dummy_batch_from_dataset",
    "make_m8_single_view_model",
    "make_win3a_model",
    "particle_setup_id_for_row",
    "probe_m8_parameter_counts",
    "probe_win3a_parameter_counts",
    "relabel_catalog_rows_for_split_seed",
    "rmse_metrics_from_l2_errors",
    "run_fusion_lr_study",
    "run_learning_rate_study",
    "run_m10_hierarchical_fusion",
    "run_m10_illumination_fusion",
    "run_m9_e2e_geometry_fusion_family",
    "run_m9_frozen_fusion_family",
    "run_split_sensitivity_study",
    "run_train_val_test_study",
    "select_lr_by_arch",
    "set_train_seed",
    "study_checkpoint_path",
    "study_checkpoint_policy",
    "study_results_dir",
]
